--@shared
ERROR_INSUFFICIENT_FUNDS = 0x00
ERROR_TRANSACTION_FAILED = 0x01
ERROR_BANNED = 0x02
ERROR_RATELIMIT_EXCEEDED = 0x03
ERROR_MONEYDB_TIMEOUT = 0x04
ERROR_BET_TOO_HIGH = 0x05
ERROR_BET_TOO_LOW = 0x06
ERROR_MONEYDB_INITIALIZING = 0x07
ERROR_NO_SESSION = 0x08
ERROR_SESSION_TIMEOUT = 0x09
ERROR_SCRIPT_ERROR = 0x0a
ERROR_UNAUTHORIZED = 0x0b
errorWidth = 8
errorLabels = {
	[ERROR_INSUFFICIENT_FUNDS] = "Insufficient funds",
	[ERROR_TRANSACTION_FAILED] = "Transaction failed",
	[ERROR_BANNED] = "You are banned",
	[ERROR_RATELIMIT_EXCEEDED] = "Ratelimit exceeded",
	[ERROR_MONEYDB_TIMEOUT] = "Host timed out",
	[ERROR_BET_TOO_HIGH] = "Bet too high",
	[ERROR_BET_TOO_LOW] = "Bet too low",
	[ERROR_MONEYDB_INITIALIZING] = "Waiting for host",
	[ERROR_NO_SESSION] = "No session",
	[ERROR_SESSION_TIMEOUT] = "Timed out",
	[ERROR_SCRIPT_ERROR] = "Script error",
	[ERROR_UNAUTHORIZED] = "Wait your turn"
}
